<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Theorem 2: Sandwich Equivalence – Structural Equivalence of Bayesian Meta-Analysis and Bayesian Survey Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch06-posterior-ccc.html" rel="next">
<link href="./ch04-isomorphism.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch04-isomorphism.html">Part II: Core Equivalence Results</a></li><li class="breadcrumb-item"><a href="./ch05-sandwich.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Theorem 2: Sandwich Equivalence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Structural Equivalence of Bayesian Meta-Analysis and Bayesian Survey Inference</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/joonho112/bayesian-meta-survey-equivalence" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch01-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Notation and Conventions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch02-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Model Definitions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch03-exactness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exactness Conditions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Core Equivalence Results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch04-isomorphism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Theorem 1: Likelihood Isomorphism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch05-sandwich.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Theorem 2: Sandwich Equivalence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch06-posterior-ccc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Corollaries 1–2: Posterior and CCC Equivalence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Design Effect Ratios</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch07-der-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">DER Framework and Transfer Theorem</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch08-conservation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conservation Law</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch09-boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Boundary Cases and Edge Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: Extensions and Interpretation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">E4-Relaxed CE and CHE Extensions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-regularity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regularity Conditions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Interpretive Issues and Practical Implications</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V: Discussion and Conclusions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discussion and Conclusions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-revision-history.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revision History</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sandwich-variance-estimator" id="toc-sandwich-variance-estimator" class="nav-link active" data-scroll-target="#sandwich-variance-estimator"><span class="header-section-number">5.1</span> Sandwich Variance Estimator</a></li>
  <li><a href="#statement" id="toc-statement" class="nav-link" data-scroll-target="#statement"><span class="header-section-number">5.2</span> Statement</a></li>
  <li><a href="#full-proof" id="toc-full-proof" class="nav-link" data-scroll-target="#full-proof"><span class="header-section-number">5.3</span> Full Proof</a>
  <ul class="collapse">
  <li><a href="#part-b-score-equivalence" id="toc-part-b-score-equivalence" class="nav-link" data-scroll-target="#part-b-score-equivalence"><span class="header-section-number">5.3.1</span> Part (b): Score Equivalence</a></li>
  <li><a href="#part-c-meat-equivalence" id="toc-part-c-meat-equivalence" class="nav-link" data-scroll-target="#part-c-meat-equivalence"><span class="header-section-number">5.3.2</span> Part (c): Meat Equivalence</a></li>
  <li><a href="#part-a-bread-equivalence" id="toc-part-a-bread-equivalence" class="nav-link" data-scroll-target="#part-a-bread-equivalence"><span class="header-section-number">5.3.3</span> Part (a): Bread Equivalence</a></li>
  <li><a href="#part-d-sandwich-equivalence" id="toc-part-d-sandwich-equivalence" class="nav-link" data-scroll-target="#part-d-sandwich-equivalence"><span class="header-section-number">5.3.4</span> Part (d): Sandwich Equivalence</a></li>
  </ul></li>
  <li><a href="#remarks" id="toc-remarks" class="nav-link" data-scroll-target="#remarks"><span class="header-section-number">5.4</span> Remarks</a>
  <ul class="collapse">
  <li><a href="#sec-remark-posterior-bread" id="toc-sec-remark-posterior-bread" class="nav-link" data-scroll-target="#sec-remark-posterior-bread"><span class="header-section-number">5.4.1</span> Remark 4 (Posterior Hessian and the Bayesian Sandwich)</a></li>
  <li><a href="#sec-remark-marginal-sandwich" id="toc-sec-remark-marginal-sandwich" class="nav-link" data-scroll-target="#sec-remark-marginal-sandwich"><span class="header-section-number">5.4.2</span> Definition 3a (Bayesian Marginal Sandwich)</a></li>
  <li><a href="#sec-sandwich-taxonomy" id="toc-sec-sandwich-taxonomy" class="nav-link" data-scroll-target="#sec-sandwich-taxonomy"><span class="header-section-number">5.4.3</span> Definition 3b (Sandwich Variant Taxonomy)</a></li>
  <li><a href="#sec-marginal-sandwich-equiv" id="toc-sec-marginal-sandwich-equiv" class="nav-link" data-scroll-target="#sec-marginal-sandwich-equiv"><span class="header-section-number">5.4.4</span> Proposition: Marginal Sandwich Equivalence</a></li>
  <li><a href="#sec-remark-small-sample" id="toc-sec-remark-small-sample" class="nav-link" data-scroll-target="#sec-remark-small-sample"><span class="header-section-number">5.4.5</span> Remark 5 (Small-Sample Corrections: HC<span class="math inline">\(a\)</span> = CR<span class="math inline">\(a\)</span>)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/joonho112/bayesian-meta-survey-equivalence/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch04-isomorphism.html">Part II: Core Equivalence Results</a></li><li class="breadcrumb-item"><a href="./ch05-sandwich.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Theorem 2: Sandwich Equivalence</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-sandwich" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Theorem 2: Sandwich Equivalence</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Theorem 1 established that the two likelihoods differ by a <span class="math inline">\(\boldsymbol{\phi}\)</span>-free constant. This chapter draws the immediate but operationally critical consequence for the sandwich variance estimator: the survey HC sandwich and the meta-analytic CR sandwich are numerically identical under the exactness conditions.</p>
<p>The argument is direct: the sandwich is assembled from scores and Hessians, and Theorem 1 guarantees that both are identical across frameworks. We begin by defining the sandwich variance estimator (Definition 3), state and prove the equivalence (Theorem 2), then develop the Bayesian marginal sandwich (Definition 3a) — a new construction that resolves the conditional-vs-marginal gap for fixed-effect inference — and establish the full sandwich variant taxonomy (Definition 3b).</p>
<section id="sandwich-variance-estimator" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sandwich-variance-estimator"><span class="header-section-number">5.1</span> Sandwich Variance Estimator</h2>
<p>Before stating Theorem 2, we define the sandwich variance estimator formally.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition 3 (Sandwich Variance Estimator)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Given a working (pseudo-)log-likelihood <span class="math inline">\(\ell(\boldsymbol{\phi}) = \sum_{j=1}^{J} \ell_j(\boldsymbol{\phi})\)</span> evaluated at a point estimate <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span> (posterior mode or MLE), the <strong>sandwich variance estimator</strong> is the <span class="math inline">\(d \times d\)</span> matrix <span id="eq-sandwich-def"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}} \;=\; \mathbf{H}^{-1}\,\mathbf{M}\,\mathbf{H}^{-1},
\tag{5.1}\]</span></span> where:</p>
<ul>
<li><p><strong>Bread</strong>: <span class="math inline">\(\mathbf{H} = -\nabla^2_{\boldsymbol{\phi}} \ell(\boldsymbol{\phi})\big|_{\hat{\boldsymbol{\phi}}}\)</span> is the negative Hessian of the log-likelihood evaluated at <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span>. This is the observed information matrix.</p></li>
<li><p><strong>Meat</strong>: <span class="math inline">\(\mathbf{M} = \sum_{j=1}^{J} \mathbf{s}_j(\hat{\boldsymbol{\phi}})\,\mathbf{s}_j(\hat{\boldsymbol{\phi}})^{\intercal}\)</span> is the sum of cluster-level score outer products evaluated at <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span>.</p></li>
<li><p><strong>Cluster-level score</strong>: <span class="math inline">\(\mathbf{s}_j(\boldsymbol{\phi}) = \nabla_{\boldsymbol{\phi}} \ell_j(\boldsymbol{\phi}) \in \mathbb{R}^d\)</span> is the gradient of the cluster-<span class="math inline">\(j\)</span> log-likelihood contribution with respect to the full parameter vector <span class="math inline">\(\boldsymbol{\phi}\)</span>.</p></li>
</ul>
</div>
</div>
<p>When the working model is correctly specified, the expected meat equals the expected bread (<span class="math inline">\(\mathbf{M} \to \mathbf{H}\)</span> in probability as <span class="math inline">\(J \to \infty\)</span> under standard regularity), and the sandwich reduces to the model-based variance <span class="math inline">\(\mathbf{H}^{-1}\)</span>. When the working model is misspecified — as is generically the case for the CE assumption of compound symmetry — the discrepancy between <span class="math inline">\(\mathbf{M}\)</span> and <span class="math inline">\(\mathbf{H}\)</span> captures the excess variability due to unmodeled dependence or heterogeneity, and the sandwich provides a consistent variance estimate regardless of working-model correctness. This is the fundamental motivation for sandwich-based inference in both the survey and meta-analytic literatures.</p>
<p>For Theorem 2, the critical structural requirement is that the additive constant <span class="math inline">\(c\)</span> from Theorem 1 decomposes as <span class="math inline">\(c = \sum_j c_j\)</span> into <em>cluster-level</em> constants that are individually <span class="math inline">\(\boldsymbol{\phi}\)</span>-free. This is stronger than the global statement <span class="math inline">\(c \not\equiv c(\boldsymbol{\phi})\)</span>: it ensures that each cluster-level score <span class="math inline">\(\mathbf{s}_j = \nabla_{\boldsymbol{\phi}} \ell_j\)</span> is separately identical across frameworks, not merely that the total score <span class="math inline">\(\sum_j \mathbf{s}_j\)</span> matches. The distinction matters because the meat matrix <span class="math inline">\(\mathbf{M} = \sum_j \mathbf{s}_j \mathbf{s}_j^{\intercal}\)</span> depends on the individual score vectors, not only their sum.</p>
</section>
<section id="statement" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="statement"><span class="header-section-number">5.2</span> Statement</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Theorem 2 (Sandwich Equivalence)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under conditions (E1)–(E3) and (E5), let <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span> be a common evaluation point (posterior mode or MLE). Then:</p>
<ol type="a">
<li><p><strong>Bread equivalence</strong>: <span class="math inline">\(\mathbf{H}_{\mathrm{surv}} = \mathbf{H}_{\mathrm{meta}}\)</span>.</p></li>
<li><p><strong>Score equivalence</strong>: <span class="math inline">\(\mathbf{s}_j^{\mathrm{surv}}(\hat{\boldsymbol{\phi}}) = \mathbf{s}_j^{\mathrm{meta}}(\hat{\boldsymbol{\phi}})\)</span> for every <span class="math inline">\(j = 1, \ldots, J\)</span>.</p></li>
<li><p><strong>Meat equivalence</strong>: <span class="math inline">\(\mathbf{M}_{\mathrm{surv}} = \mathbf{M}_{\mathrm{meta}}\)</span>.</p></li>
<li><p><strong>Sandwich equivalence</strong>: <span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{surv}} = \mathbf{H}_{\mathrm{surv}}^{-1}\,\mathbf{M}_{\mathrm{surv}}\,\mathbf{H}_{\mathrm{surv}}^{-1} = \mathbf{H}_{\mathrm{meta}}^{-1}\,\mathbf{M}_{\mathrm{meta}}\,\mathbf{H}_{\mathrm{meta}}^{-1} = \mathbf{V}_{\mathrm{sand}}^{\mathrm{meta}}\)</span>.</p></li>
</ol>
<p>In particular, the survey HC<span class="math inline">\(a\)</span> sandwich variance estimator and the meta-analytic CR<span class="math inline">\(a\)</span> robust variance estimator are numerically identical for <span class="math inline">\(a = 0, 1, 2, 3\)</span>.</p>
</div>
</div>
<p>The following figure illustrates Theorem 2 using the same toy matched example from <a href="ch04-isomorphism.html#fig-likelihood-isomorphism" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>. <a href="#fig-sandwich-matrix-equivalence" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> displays the posterior bread, the meat, and the resulting sandwich variance side by side for the meta-analytic and survey frameworks. The difference row vanishes numerically, making the equality of every matrix building block visually explicit.</p>
<div id="fig-sandwich-matrix-equivalence" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sandwich-matrix-equivalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/matlab/fig03_sandwich_matrix_equivalence.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sandwich-matrix-equivalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Toy matched-example heatmaps of the posterior bread <span class="math inline">\(\mathbf{H}^{\mathrm{post}}\)</span>, the meat <span class="math inline">\(\mathbf{M}\)</span>, and the resulting sandwich variance <span class="math inline">\(\mathbf{V}_{\mathrm{sand}}\)</span> for the meta-analytic and survey sides. The difference row vanishes numerically, confirming Theorem 2: the sandwich machinery is identical across the two frameworks under the exactness conditions.
</figcaption>
</figure>
</div>
</section>
<section id="full-proof" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="full-proof"><span class="header-section-number">5.3</span> Full Proof</h2>
<p>The proof proceeds in four steps, establishing parts (b), (c), (a), and (d) in that order. We present score equivalence first because it is the logical foundation: meat equivalence follows from score equivalence, and bread equivalence follows from Hessian equivalence (Theorem 1(b)). The sandwich is then assembled from its three ingredients.</p>
<section id="part-b-score-equivalence" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="part-b-score-equivalence"><span class="header-section-number">5.3.1</span> Part (b): Score Equivalence</h3>
<p>By Theorem 1, the global log-likelihoods satisfy <span class="math inline">\(\ell^{(w)}_{\mathrm{surv}}(\boldsymbol{\phi}) = \ell_{\mathrm{meta}}(\boldsymbol{\phi}) + c\)</span>, where <span class="math inline">\(c\)</span> does not depend on <span class="math inline">\(\boldsymbol{\phi}\)</span>. The crucial structural property, established in <a href="ch04-isomorphism.html#sec-remark-constant-c" class="quarto-xref"><span>Section 4.3.3</span></a>, is that <span class="math inline">\(c\)</span> decomposes additively over clusters: <span class="math display">\[
c = \sum_{j=1}^{J} c_j,
\]</span> where each <span class="math inline">\(c_j = -\frac{n_j}{2}\log(\sigma^2_{e,j}/\bar{s}_j^2)\)</span> depends on <span class="math inline">\(\sigma^2_{e,j}\)</span>, <span class="math inline">\(\bar{s}_j^2\)</span>, <span class="math inline">\(\rho\)</span>, and <span class="math inline">\(n_j\)</span> but not on <span class="math inline">\(\boldsymbol{\phi}\)</span>.</p>
<p>It follows that the cluster-level log-likelihoods also differ by a <span class="math inline">\(\boldsymbol{\phi}\)</span>-free constant: <span class="math display">\[
\ell_j^{(w)}(\boldsymbol{\phi}) = \ell_j^{\mathrm{meta}}(\boldsymbol{\phi}) + c_j, \quad j = 1, \ldots, J.
\]</span></p>
<p>Taking the gradient with respect to <span class="math inline">\(\boldsymbol{\phi}\)</span>: <span id="eq-score-equiv-cluster"><span class="math display">\[
\mathbf{s}_j^{\mathrm{surv}}(\boldsymbol{\phi}) = \nabla_{\boldsymbol{\phi}}\,\ell_j^{(w)}(\boldsymbol{\phi}) = \nabla_{\boldsymbol{\phi}}\,\ell_j^{\mathrm{meta}}(\boldsymbol{\phi}) + \underbrace{\nabla_{\boldsymbol{\phi}}\, c_j}_{= \,\mathbf{0}} = \mathbf{s}_j^{\mathrm{meta}}(\boldsymbol{\phi}).
\tag{5.2}\]</span></span></p>
<p>Since <span class="math inline">\(c_j\)</span> does not depend on <span class="math inline">\(\boldsymbol{\phi}\)</span>, its gradient vanishes. Equation <a href="#eq-score-equiv-cluster" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> holds at every <span class="math inline">\(\boldsymbol{\phi} \in \mathbb{R}^d\)</span>, and in particular at <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span>: <span class="math display">\[
\mathbf{s}_j^{\mathrm{surv}}(\hat{\boldsymbol{\phi}}) = \mathbf{s}_j^{\mathrm{meta}}(\hat{\boldsymbol{\phi}}), \quad j = 1, \ldots, J. \quad\square
\]</span></p>
</section>
<section id="part-c-meat-equivalence" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="part-c-meat-equivalence"><span class="header-section-number">5.3.2</span> Part (c): Meat Equivalence</h3>
<p>The meat matrix is defined as the sum of cluster-level score outer products. By part (b), the cluster-level scores are identical: <span id="eq-meat-equiv"><span class="math display">\[
\begin{aligned}
\mathbf{M}_{\mathrm{surv}} &amp;= \sum_{j=1}^{J} \mathbf{s}_j^{\mathrm{surv}}(\hat{\boldsymbol{\phi}})\,\bigl[\mathbf{s}_j^{\mathrm{surv}}(\hat{\boldsymbol{\phi}})\bigr]^{\intercal} \\
&amp;= \sum_{j=1}^{J} \mathbf{s}_j^{\mathrm{meta}}(\hat{\boldsymbol{\phi}})\,\bigl[\mathbf{s}_j^{\mathrm{meta}}(\hat{\boldsymbol{\phi}})\bigr]^{\intercal} \\
&amp;= \mathbf{M}_{\mathrm{meta}}.
\end{aligned}
\tag{5.3}\]</span></span></p>
<p>Each term in the sum is a <span class="math inline">\(d \times d\)</span> rank-one matrix <span class="math inline">\(\mathbf{s}_j \mathbf{s}_j^{\intercal}\)</span>, and the substitution is term by term. <span class="math inline">\(\square\)</span></p>
</section>
<section id="part-a-bread-equivalence" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="part-a-bread-equivalence"><span class="header-section-number">5.3.3</span> Part (a): Bread Equivalence</h3>
<p>By Theorem 1(b), the Hessian matrices are identical at every <span class="math inline">\(\boldsymbol{\phi}\)</span>: <span class="math display">\[
\nabla^2_{\boldsymbol{\phi}}\,\ell^{(w)}_{\mathrm{surv}}(\boldsymbol{\phi}) = \nabla^2_{\boldsymbol{\phi}}\,\ell_{\mathrm{meta}}(\boldsymbol{\phi}).
\]</span></p>
<p>Taking negatives and evaluating at <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span>: <span id="eq-bread-equiv"><span class="math display">\[
\mathbf{H}_{\mathrm{surv}} = -\nabla^2_{\boldsymbol{\phi}}\,\ell^{(w)}_{\mathrm{surv}}\big|_{\hat{\boldsymbol{\phi}}} = -\nabla^2_{\boldsymbol{\phi}}\,\ell_{\mathrm{meta}}\big|_{\hat{\boldsymbol{\phi}}} = \mathbf{H}_{\mathrm{meta}}.
\tag{5.4}\]</span></span></p>
<p><span class="math inline">\(\square\)</span></p>
</section>
<section id="part-d-sandwich-equivalence" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="part-d-sandwich-equivalence"><span class="header-section-number">5.3.4</span> Part (d): Sandwich Equivalence</h3>
<p>Substituting parts (a) and (c) into Definition 3 (<a href="#eq-sandwich-def" class="quarto-xref">Equation&nbsp;<span>5.1</span></a>): <span id="eq-sandwich-equiv"><span class="math display">\[
\begin{aligned}
\mathbf{V}_{\mathrm{sand}}^{\mathrm{surv}} &amp;= \mathbf{H}_{\mathrm{surv}}^{-1}\,\mathbf{M}_{\mathrm{surv}}\,\mathbf{H}_{\mathrm{surv}}^{-1} \\
&amp;= \mathbf{H}_{\mathrm{meta}}^{-1}\,\mathbf{M}_{\mathrm{meta}}\,\mathbf{H}_{\mathrm{meta}}^{-1} \\
&amp;= \mathbf{V}_{\mathrm{sand}}^{\mathrm{meta}}.
\end{aligned}
\tag{5.5}\]</span></span></p>
<p><span class="math inline">\(\quad\blacksquare\)</span></p>
<p>Theorem 2 extends the equivalence chain from likelihoods to variance estimators. The survey HC sandwich and the meta-analytic CR sandwich — developed by separate literatures for separate purposes — are the same matrix when evaluated under the exactness conditions. The practical consequence is immediate: any sandwich-based diagnostic or correction available in one tradition applies equally in the other. The Remarks that follow explore the posterior Hessian, the Bayesian marginal sandwich for fixed effects, the sandwich variant taxonomy, and the novel structural identification HC<span class="math inline">\(_a\)</span> = CR<span class="math inline">\(_a\)</span>.</p>
</section>
</section>
<section id="remarks" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="remarks"><span class="header-section-number">5.4</span> Remarks</h2>
<section id="sec-remark-posterior-bread" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="sec-remark-posterior-bread"><span class="header-section-number">5.4.1</span> Remark 4 (Posterior Hessian and the Bayesian Sandwich)</h3>
<p>In the Bayesian setting, the sandwich variance estimator is typically computed using the <strong>posterior Hessian</strong> rather than the likelihood-only Hessian. The posterior Hessian includes the curvature contribution from the prior: <span id="eq-posterior-hessian"><span class="math display">\[
\mathbf{H}^{\mathrm{post}} = \mathbf{H} + \mathbf{H}_{\mathrm{prior}},
\tag{5.6}\]</span></span> where <span class="math inline">\(\mathbf{H}_{\mathrm{prior}} = -\nabla^2_{\boldsymbol{\phi}} \log p(\boldsymbol{\phi})\big|_{\hat{\boldsymbol{\phi}}}\)</span> collects the prior precision contributions. For the hierarchical normal model: <span class="math display">\[
\mathbf{H}_{\mathrm{prior}} = \mathrm{diag}\!\left(\mathbf{H}_{\mathrm{prior}}^{\boldsymbol{\beta}},\; \sigma_\theta^{-2}\mathbf{I}_J\right),
\]</span> where <span class="math inline">\(\mathbf{H}_{\mathrm{prior}}^{\boldsymbol{\beta}}\)</span> is the prior precision for <span class="math inline">\(\boldsymbol{\beta}\)</span> and <span class="math inline">\(\sigma_\theta^{-2}\mathbf{I}_J\)</span> comes from the <span class="math inline">\(\textsf{N}(0, \sigma^2_\theta)\)</span> prior on the random effects.</p>
<p>Since both frameworks use the same prior on <span class="math inline">\((\boldsymbol{\beta}, \sigma^2_\theta)\)</span> and the same random-effects distribution, the prior Hessians are identical: <span class="math display">\[
\mathbf{H}_{\mathrm{prior}}^{\mathrm{surv}} = \mathbf{H}_{\mathrm{prior}}^{\mathrm{meta}}.
\]</span></p>
<p>Combined with Theorem 2(a), the posterior bread is also identical: <span class="math display">\[
\mathbf{H}^{\mathrm{post}}_{\mathrm{surv}} = \mathbf{H}_{\mathrm{surv}} + \mathbf{H}_{\mathrm{prior}}^{\mathrm{surv}} = \mathbf{H}_{\mathrm{meta}} + \mathbf{H}_{\mathrm{prior}}^{\mathrm{meta}} = \mathbf{H}^{\mathrm{post}}_{\mathrm{meta}}.
\]</span></p>
<p><strong>Critical clarification on the meat.</strong> While the bread may use either the likelihood-only Hessian <span class="math inline">\(\mathbf{H}\)</span> or the posterior Hessian <span class="math inline">\(\mathbf{H}^{\mathrm{post}}\)</span> (both are equivalent across frameworks), the <strong>meat <span class="math inline">\(\mathbf{M}\)</span> must always use likelihood-only scores</strong>. That is, <span class="math display">\[
\mathbf{M} = \sum_{j=1}^{J} \mathbf{s}_j(\hat{\boldsymbol{\phi}})\,\mathbf{s}_j(\hat{\boldsymbol{\phi}})^{\intercal}, \quad \text{where} \quad \mathbf{s}_j(\boldsymbol{\phi}) = \nabla_{\boldsymbol{\phi}}\,\ell_j(\boldsymbol{\phi}),
\]</span> and <span class="math inline">\(\ell_j\)</span> is the cluster-<span class="math inline">\(j\)</span> <strong>likelihood</strong> contribution, not the posterior contribution. The reason is conceptual: the meat estimates the variance of the score under the true data-generating process. The prior is not part of the data-generating process; it is a modeling choice. Including prior score contributions in the meat would conflate model uncertainty (captured by the prior) with sampling uncertainty (captured by the meat), producing an inconsistent variance estimate.</p>
<p>In implementation, this means:</p>
<ul>
<li><strong>Bread options</strong>: <span class="math inline">\((\mathbf{H}^{\mathrm{post}})^{-1} \mathbf{M}\, (\mathbf{H}^{\mathrm{post}})^{-1}\)</span> (posterior Hessian bread) or <span class="math inline">\(\mathbf{H}^{-1} \mathbf{M}\, \mathbf{H}^{-1}\)</span> (likelihood-only bread). Both are valid; the posterior Hessian version is standard in the Bayesian sandwich correction literature <span class="citation" data-cites="WilliamsSavitsky2021">(<a href="#ref-WilliamsSavitsky2021" role="doc-biblioref">Williams and Savitsky 2021</a>)</span>.</li>
<li><strong>Meat</strong>: Always <span class="math inline">\(\mathbf{M} = \sum_j \mathbf{s}_j \mathbf{s}_j^{\intercal}\)</span> with <span class="math inline">\(\mathbf{s}_j = \nabla_{\boldsymbol{\phi}} \ell_j\)</span> (likelihood-only). <strong>Never</strong> <span class="math inline">\(\nabla_{\boldsymbol{\phi}}[\ell_j + \log p]\)</span>.</li>
</ul>
<p>This distinction requires explicit clarification. The sandwich equivalence of Theorem 2 holds regardless of whether the bread uses <span class="math inline">\(\mathbf{H}\)</span> or <span class="math inline">\(\mathbf{H}^{\mathrm{post}}\)</span>, because both are identical across frameworks. The meat is identical because Theorem 1’s additive constant <span class="math inline">\(c\)</span> decomposes into cluster-level constants <span class="math inline">\(c_j\)</span> that do not depend on <span class="math inline">\(\boldsymbol{\phi}\)</span>.</p>
<p><strong>Conditional nature of the full-joint sandwich.</strong> An important operational consequence of the likelihood-only meat is that the full-joint sandwich <span class="math inline">\(\mathbf{V}_{\mathrm{sand}} = (\mathbf{H}^{\mathrm{post}})^{-1}\mathbf{M}(\mathbf{H}^{\mathrm{post}})^{-1}\)</span> produces <strong>conditional</strong> variance estimates for the fixed effects <span class="math inline">\(\boldsymbol{\beta}\)</span>. Specifically, the scores <span class="math inline">\(\mathbf{s}_j(\hat{\boldsymbol{\phi}})\)</span> are evaluated at the posterior mean <span class="math inline">\(\hat{\boldsymbol{\phi}} = (\hat{\boldsymbol{\beta}}^{\intercal}, \hat{\boldsymbol{\theta}}^{\intercal})^{\intercal}\)</span> of the <strong>full joint model</strong>, where each <span class="math inline">\(\hat{\theta}_j\)</span> absorbs the study-level variation. Consequently, the study-level residuals <span class="math inline">\(\bar{r}_j = \bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}} - \hat{\theta}_j\)</span> are approximately zero at the posterior mean, making the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the meat near-zero: <span class="math display">\[
[\mathbf{M}]_{\boldsymbol{\beta}\boldsymbol{\beta}} = \sum_{j=1}^{J} \mathbf{s}_j^{\boldsymbol{\beta}}\,(\mathbf{s}_j^{\boldsymbol{\beta}})^{\intercal} \approx \mathbf{0},
\]</span> and therefore <span class="math inline">\([\mathbf{V}_{\mathrm{sand}}]_{\boldsymbol{\beta}\boldsymbol{\beta}}\)</span> is much smaller than the marginal (cluster-robust) sandwich SE<span class="math inline">\(^2_{\mathrm{CR2}}(\boldsymbol{\beta})\)</span>.</p>
<p>This is <strong>expected behavior</strong>, not a computational error. The full-joint sandwich captures the variance of <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> <strong>conditional on the realized</strong> <span class="math inline">\(\hat{\boldsymbol{\theta}}\)</span>, while a marginal sandwich estimates <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}})\)</span> <strong>marginalizing over</strong> <span class="math inline">\(\boldsymbol{\theta}\)</span>. For the blockwise CCC of <span class="math inline">\(\boldsymbol{\beta}\)</span>, the <strong>marginal</strong> sandwich is the appropriate target because inference on <span class="math inline">\(\boldsymbol{\beta}\)</span> integrates over the random-effects distribution. This motivates the Bayesian marginal sandwich developed in Remark 4b below and the blockwise approach described in <a href="ch06-posterior-ccc.html#sec-blockwise-ccc" class="quarto-xref"><span>Section 6.2.2</span></a>.</p>
<p>Empirically, using the TSL15 data: the full-joint analytical sandwich gives <span class="math inline">\(\mathrm{SD}_{\mathrm{sand}}(\mu) \approx 0.007\)</span>, while the marginal CR2 gives <span class="math inline">\(\mathrm{SE}_{\mathrm{CR2}}(\mu) \approx 0.021\)</span> — a factor of 3, reflecting exactly the conditional-vs-marginal gap predicted by the theory.</p>
</section>
<section id="sec-remark-marginal-sandwich" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="sec-remark-marginal-sandwich"><span class="header-section-number">5.4.2</span> Definition 3a (Bayesian Marginal Sandwich)</h3>
<p>The conditional-vs-marginal gap described above can be resolved <em>within a purely Bayesian framework</em> by analytically integrating out the study-specific random effects <span class="math inline">\(\theta_j\)</span> before constructing the sandwich. The <strong>closed-form derivation below is exact when the linear predictor is cluster-constant within each study</strong> (intercept-only or study-level covariates, i.e., the setting of condition (E4)). In that case the sandwich operates on the <span class="math inline">\((K+1)\)</span>-dimensional parameter vector <span class="math inline">\((\boldsymbol{\beta}, \tau^2)\)</span> rather than the full <span class="math inline">\((K+J)\)</span>-dimensional vector <span class="math inline">\((\boldsymbol{\beta}, \boldsymbol{\theta})\)</span>. We develop this special-case construction in three steps: (i) deriving the marginal likelihood, (ii) computing the marginal scores and Hessian, and (iii) assembling the sandwich.</p>
<section id="sec-marginal-likelihood-derivation" class="level4">
<h4 class="anchored" data-anchor-id="sec-marginal-likelihood-derivation">Step 1: Marginal likelihood derivation</h4>
<p>Under the CE meta-analytic model, and <strong>assuming the linear predictor is cluster-constant within study</strong> (<span class="math inline">\(\mathbf{x}_{ij}=\mathbf{x}_j\)</span> for all <span class="math inline">\(i\)</span>), the joint likelihood for study <span class="math inline">\(j\)</span> is <span id="eq-joint-lik-j"><span class="math display">\[
p(\mathbf{y}_j \mid \boldsymbol{\beta}, \theta_j) = \prod_{i=1}^{n_j} \textsf{N}\!\left(y_{ij} \mid \mathbf{x}_{ij}^{\intercal}\boldsymbol{\beta} + \theta_j,\; \bar{s}_j^2\right),
\tag{5.7}\]</span></span> where <span class="math inline">\(\bar{s}_j^2\)</span> is the (known) within-study sampling variance under the (E2) specification. Under the cluster-constant linear predictor assumption, the study-level sufficient statistic for <span class="math inline">\((\boldsymbol{\beta}, \theta_j)\)</span> is <span class="math inline">\(\bar{y}_j = n_j^{-1}\sum_{i=1}^{n_j} y_{ij}\)</span>, with conditional distribution: <span id="eq-ybar-cond"><span class="math display">\[
\bar{y}_j \mid \boldsymbol{\beta}, \theta_j \;\sim\; \textsf{N}\!\left(\mathbf{\bar{x}}_j^{\intercal}\boldsymbol{\beta} + \theta_j,\; \frac{\bar{s}_j^2}{n_j}\right).
\tag{5.8}\]</span></span></p>
<p>To obtain the marginal likelihood, we integrate over the random-effects distribution <span class="math inline">\(\theta_j \sim \textsf{N}(0, \tau^2)\)</span>: <span id="eq-marginal-integral"><span class="math display">\[
p(\bar{y}_j \mid \boldsymbol{\beta}, \tau^2) = \int_{-\infty}^{\infty} \textsf{N}\!\left(\bar{y}_j \mid \mathbf{\bar{x}}_j^{\intercal}\boldsymbol{\beta} + \theta_j,\; \frac{\bar{s}_j^2}{n_j}\right) \cdot \textsf{N}(\theta_j \mid 0, \tau^2)\; d\theta_j.
\tag{5.9}\]</span></span></p>
<p>This is a convolution of two Gaussian densities. Using the identity <span class="math inline">\(\textsf{N}(z \mid a, \sigma_1^2) \cdot \textsf{N}(a \mid b, \sigma_2^2) \propto \textsf{N}(z \mid b, \sigma_1^2 + \sigma_2^2) \cdot \textsf{N}(a \mid m, v)\)</span> (where <span class="math inline">\(m\)</span> and <span class="math inline">\(v\)</span> are functions of <span class="math inline">\(z, b, \sigma_1^2, \sigma_2^2\)</span>), the integral evaluates to: <span id="eq-marginal-density"><span class="math display">\[
p(\bar{y}_j \mid \boldsymbol{\beta}, \tau^2) = \textsf{N}\!\left(\bar{y}_j \;\Big|\; \mathbf{\bar{x}}_j^{\intercal}\boldsymbol{\beta},\; \underbrace{\frac{\bar{s}_j^2}{n_j} + \tau^2}_{=\; v_j}\right).
\tag{5.10}\]</span></span></p>
<p>Defining <span class="math inline">\(v_j = \bar{s}_j^2/n_j + \tau^2\)</span> and the study-level residual <span class="math inline">\(r_j = \bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\boldsymbol{\beta}\)</span>, the marginal log-likelihood for study <span class="math inline">\(j\)</span> is: <span id="eq-marginal-loglik-j"><span class="math display">\[
\ell_j^{\mathrm{marg}}(\boldsymbol{\beta}, \tau^2) = -\frac{1}{2}\log(2\pi) - \frac{1}{2}\log v_j - \frac{r_j^2}{2v_j}.
\tag{5.11}\]</span></span></p>
<p>The total marginal log-likelihood is <span class="math inline">\(\ell^{\mathrm{marg}}(\boldsymbol{\beta}, \tau^2) = \sum_{j=1}^{J} \ell_j^{\mathrm{marg}}(\boldsymbol{\beta}, \tau^2)\)</span>.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition 3a (Bayesian Marginal Sandwich)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Marginal CE model (closed-form special case).</strong> Under the CE meta-analytic model with the <strong>independence working model</strong> (<span class="math inline">\(\rho_{\mathrm{work}} = 0\)</span>) and a <strong>cluster-constant linear predictor</strong> within study, integrating <span class="math inline">\(\theta_j \sim \textsf{N}(0, \tau^2)\)</span> out of the joint likelihood yields the marginal model: <span id="eq-marginal-ce"><span class="math display">\[
\bar{y}_j \mid \boldsymbol{\beta}, \tau^2 \;\sim\; \textsf{N}\!\left(\mathbf{\bar{x}}_j^{\intercal}\boldsymbol{\beta},\; v_j\right), \quad v_j = \frac{\bar{s}_j^2}{n_j} + \tau^2,
\tag{5.12}\]</span></span> where <span class="math inline">\(\bar{y}_j = n_j^{-1}\sum_{i} y_{ij}\)</span> and <span class="math inline">\(\mathbf{\bar{x}}_j = n_j^{-1}\sum_{i} \mathbf{x}_{ij}\)</span> are the study-level sufficient statistics.</p>
<p><strong>Scope limitation.</strong> ⚠️ The cluster-mean reduction above is exact only when the linear predictor is constant within study (intercept-only or study-level covariates) and <span class="math inline">\(\rho_{\mathrm{work}}=0\)</span>. For general within-study-varying covariates, the exact marginal model is the full vector model <span class="math display">\[
\mathbf{y}_j \mid \boldsymbol{\beta}, \tau^2 \sim \textsf{N}\!\left(\mathbf{X}_j\boldsymbol{\beta},\; \bar{s}_j^2\mathbf{I}_{n_j} + \tau^2\mathbf{1}_{n_j}\mathbf{1}_{n_j}^{\intercal}\right),
\]</span> and the marginal sandwich must be written in full matrix form. The present closed-form formulas therefore apply to the intercept-only and study-level-covariate case; the abstract marginal equivalence proposition proved later in this chapter is more general.</p>
</div>
</div>
</section>
<section id="sec-marginal-scores-hessian" class="level4">
<h4 class="anchored" data-anchor-id="sec-marginal-scores-hessian">Step 2: Marginal scores and Hessian</h4>
<p><strong>Marginal scores.</strong> Differentiating <a href="#eq-marginal-loglik-j" class="quarto-xref">Equation&nbsp;<span>5.11</span></a> with respect to <span class="math inline">\(\boldsymbol{\beta}\)</span> and <span class="math inline">\(\tau^2\)</span>:</p>
<p><em><span class="math inline">\(\boldsymbol{\beta}\)</span>-score:</em> <span id="eq-score-beta-deriv"><span class="math display">\[
\frac{\partial \ell_j^{\mathrm{marg}}}{\partial \boldsymbol{\beta}} = \frac{r_j}{v_j}\,\mathbf{\bar{x}}_j,
\tag{5.13}\]</span></span> since <span class="math inline">\(\partial r_j / \partial \boldsymbol{\beta} = -\mathbf{\bar{x}}_j\)</span> and <span class="math inline">\(\partial(-r_j^2/2v_j)/\partial \boldsymbol{\beta} = r_j\,\mathbf{\bar{x}}_j / v_j\)</span>.</p>
<p><em><span class="math inline">\(\tau^2\)</span>-score:</em> Using <span class="math inline">\(\partial v_j/\partial \tau^2 = 1\)</span>: <span id="eq-score-tau2-deriv"><span class="math display">\[
\frac{\partial \ell_j^{\mathrm{marg}}}{\partial \tau^2} = -\frac{1}{2v_j} + \frac{r_j^2}{2v_j^2}.
\tag{5.14}\]</span></span></p>
<p>Combining into the <span class="math inline">\((K+1)\)</span>-vector <span class="math inline">\(\mathbf{s}_j(\boldsymbol{\xi}) = (\mathbf{s}_j(\boldsymbol{\beta})^{\intercal}, s_j(\tau^2))^{\intercal}\)</span> with <span class="math inline">\(\boldsymbol{\xi} = (\boldsymbol{\beta}^{\intercal}, \tau^2)^{\intercal}\)</span>: <span id="eq-marginal-scores"><span class="math display">\[
s_j(\boldsymbol{\beta}) = \frac{r_j \,\mathbf{\bar{x}}_j}{v_j}, \qquad s_j(\tau^2) = -\frac{1}{2v_j} + \frac{r_j^2}{2v_j^2}.
\tag{5.15}\]</span></span></p>
<p><strong>Marginal Hessian.</strong> The second derivatives of <span class="math inline">\(\ell^{\mathrm{marg}}(\boldsymbol{\xi}) = \sum_j \ell_j^{\mathrm{marg}}(\boldsymbol{\xi})\)</span> are:</p>
<p><em><span class="math inline">\(\boldsymbol{\beta}\boldsymbol{\beta}\)</span>-block:</em> <span id="eq-hess-beta-beta"><span class="math display">\[
-\frac{\partial^2 \ell^{\mathrm{marg}}}{\partial \boldsymbol{\beta}\,\partial \boldsymbol{\beta}^{\intercal}} = \sum_{j=1}^{J} \frac{\mathbf{\bar{x}}_j\,\mathbf{\bar{x}}_j^{\intercal}}{v_j},
\tag{5.16}\]</span></span> which is the weighted normal equations matrix with weights <span class="math inline">\(w_j = 1/v_j\)</span>.</p>
<p><em><span class="math inline">\(\tau^2\tau^2\)</span>-block:</em> <span id="eq-hess-tau2-tau2"><span class="math display">\[
-\frac{\partial^2 \ell^{\mathrm{marg}}}{\partial (\tau^2)^2} = \sum_{j=1}^{J} \left(-\frac{1}{2v_j^2} + \frac{r_j^2}{v_j^3}\right).
\tag{5.17}\]</span></span></p>
<p><em><span class="math inline">\(\boldsymbol{\beta}\tau^2\)</span>-cross block:</em> <span id="eq-hess-beta-tau2"><span class="math display">\[
-\frac{\partial^2 \ell^{\mathrm{marg}}}{\partial \boldsymbol{\beta}\,\partial \tau^2} = \sum_{j=1}^{J} \frac{r_j\,\mathbf{\bar{x}}_j}{v_j^2}.
\tag{5.18}\]</span></span></p>
<p>The marginal posterior Hessian adds the prior curvature: <span id="eq-marginal-posterior-hessian"><span class="math display">\[
\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}} = -\nabla^2_{\boldsymbol{\xi}} \ell^{\mathrm{marg}}(\boldsymbol{\xi})\big|_{\hat{\boldsymbol{\xi}}} + \mathbf{H}_{\mathrm{prior}}^{\boldsymbol{\xi}},
\tag{5.19}\]</span></span> where <span class="math inline">\(\mathbf{H}_{\mathrm{prior}}^{\boldsymbol{\xi}}\)</span> collects the prior precision contributions for <span class="math inline">\((\boldsymbol{\beta}, \tau^2)\)</span>.</p>
</section>
<section id="sec-marginal-sandwich-assembly" class="level4">
<h4 class="anchored" data-anchor-id="sec-marginal-sandwich-assembly">Step 3: Marginal sandwich assembly</h4>
<p>With <span class="math inline">\(\boldsymbol{\xi} = (\boldsymbol{\beta}^{\intercal}, \tau^2)^{\intercal} \in \mathbb{R}^{K+1}\)</span>, the <strong>Bayesian marginal sandwich</strong> is <span id="eq-marginal-sandwich-def"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}} = (\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}})^{-1}\,\mathbf{M}_{\mathrm{marg}}\,(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}})^{-1},
\tag{5.20}\]</span></span> where:</p>
<ul>
<li><strong>Marginal meat</strong>: <span class="math inline">\(\mathbf{M}_{\mathrm{marg}} = \sum_{j=1}^{J} \mathbf{s}_j(\hat{\boldsymbol{\xi}})\,\mathbf{s}_j(\hat{\boldsymbol{\xi}})^{\intercal} = \mathbf{S}^{\intercal}\mathbf{S}\)</span>, a <span class="math inline">\((K+1) \times (K+1)\)</span> matrix, with the <span class="math inline">\(J \times (K+1)\)</span> score matrix <span class="math inline">\(\mathbf{S}\)</span> having row <span class="math inline">\(j\)</span> equal to <span class="math inline">\(\mathbf{s}_j(\hat{\boldsymbol{\xi}})^{\intercal}\)</span>.</li>
<li><strong>Marginal bread</strong>: <span class="math inline">\(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}}\)</span> as defined in <a href="#eq-marginal-posterior-hessian" class="quarto-xref">Equation&nbsp;<span>5.19</span></a>.</li>
</ul>
<p>Because the random effects have been integrated out, the marginal meat <span class="math inline">\([\mathbf{M}_{\mathrm{marg}}]_{\boldsymbol{\beta}\boldsymbol{\beta}}\)</span> captures the <strong>full between-study variation</strong> in the residuals <span class="math inline">\(r_j\)</span>, including the component due to <span class="math inline">\(\theta_j \sim \textsf{N}(0, \tau^2)\)</span>. This resolves the near-zero conditional meat problem: <span class="math inline">\([\mathbf{M}_{\mathrm{marg}}]_{\boldsymbol{\beta}\boldsymbol{\beta}} \gg [\mathbf{M}_{\mathrm{joint}}]_{\boldsymbol{\beta}\boldsymbol{\beta}} \approx \mathbf{0}\)</span>.</p>
<p><strong>Proof that the conditional meat is near-zero.</strong> To see why the marginal integration resolves the gap, note that the full-joint <span class="math inline">\(\boldsymbol{\beta}\)</span>-score for study <span class="math inline">\(j\)</span> is <span class="math inline">\(s_j^{\mathrm{joint}}(\boldsymbol{\beta}) = n_j(\bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}} - \hat{\theta}_j)\,\mathbf{\bar{x}}_j / \bar{s}_j^2\)</span>. At the posterior mean, <span class="math inline">\(\hat{\theta}_j \approx \bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}} - (1-B_j)(\bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}}) = B_j\,r_j\)</span>, so <span class="math inline">\(\bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}} - \hat{\theta}_j = (1-B_j)\,r_j \approx 0\)</span> when <span class="math inline">\(B_j\)</span> is large. By contrast, the marginal <span class="math inline">\(\boldsymbol{\beta}\)</span>-score is <span class="math inline">\(s_j^{\mathrm{marg}}(\boldsymbol{\beta}) = r_j\,\mathbf{\bar{x}}_j/v_j\)</span>, where <span class="math inline">\(r_j = \bar{y}_j - \mathbf{\bar{x}}_j^{\intercal}\hat{\boldsymbol{\beta}}\)</span> retains the <strong>full</strong> study-level residual because <span class="math inline">\(\theta_j\)</span> has been integrated out.</p>
</section>
<section id="sec-profile-derivation" class="level4">
<h4 class="anchored" data-anchor-id="sec-profile-derivation">Profile sandwich and its relationship to the marginal sandwich</h4>
<p><strong>Profile sandwich.</strong> A further simplification is obtained by fixing <span class="math inline">\(\tau^2 = \hat{\tau}^2\)</span> (the posterior mean or mode) and sandwiching only the <span class="math inline">\(K\)</span>-dimensional <span class="math inline">\(\boldsymbol{\beta}\)</span> vector. This is equivalent to extracting the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the marginal sandwich while ignoring the <span class="math inline">\(\tau^2\)</span> estimation uncertainty: <span id="eq-profile-sandwich"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}} = (H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}})^{-1}\,[\mathbf{M}_{\mathrm{marg}}]_{\boldsymbol{\beta}\boldsymbol{\beta}}\,(H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}})^{-1},
\tag{5.21}\]</span></span> where <span class="math inline">\(H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}} = \sum_j \mathbf{\bar{x}}_j\,\mathbf{\bar{x}}_j^{\intercal}/v_j + H_{\mathrm{prior},\boldsymbol{\beta}\boldsymbol{\beta}}\)</span> and <span class="math inline">\([\mathbf{M}_{\mathrm{marg}}]_{\boldsymbol{\beta}\boldsymbol{\beta}} = \sum_j r_j^2\,\mathbf{\bar{x}}_j\,\mathbf{\bar{x}}_j^{\intercal}/v_j^2\)</span>.</p>
<p><strong>Proposition (Profile–Marginal Relationship).</strong> The profile sandwich <span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}}\)</span> and the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the full marginal sandwich <span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}[\boldsymbol{\beta}, \boldsymbol{\beta}]\)</span> satisfy <span id="eq-profile-marginal-relation"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}} = \mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}[\boldsymbol{\beta}, \boldsymbol{\beta}] - \boldsymbol{\Delta},
\tag{5.22}\]</span></span> where the correction <span class="math inline">\(\boldsymbol{\Delta}\)</span> captures the contribution of <span class="math inline">\(\tau^2\)</span> estimation uncertainty to <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}})\)</span> through the off-diagonal blocks of the <span class="math inline">\((K+1)\)</span>-dimensional inverse. When the <span class="math inline">\(\boldsymbol{\beta}\)</span>-<span class="math inline">\(\tau^2\)</span> correlation is weak (as is typical when <span class="math inline">\(J\)</span> is large), <span class="math inline">\(\boldsymbol{\Delta} \approx \mathbf{0}\)</span> and the two sandwiches agree closely.</p>
<p><em>Sketch of proof.</em> Let <span class="math inline">\(\mathbf{A} = \mathbf{H}_{\mathrm{marg}}^{\mathrm{post}}\)</span> be the <span class="math inline">\((K+1) \times (K+1)\)</span> posterior Hessian partitioned as <span class="math inline">\(\mathbf{A} = \begin{pmatrix} \mathbf{A}_{11} &amp; \mathbf{a}_{12} \\ \mathbf{a}_{12}^{\intercal} &amp; a_{22}\end{pmatrix}\)</span> (with <span class="math inline">\(\mathbf{A}_{11} = H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}}\)</span>). By the partitioned inverse formula, <span class="math inline">\([\mathbf{A}^{-1}]_{11} = \mathbf{A}_{11}^{-1} + \mathbf{A}_{11}^{-1}\mathbf{a}_{12}\,c\,\mathbf{a}_{12}^{\intercal}\mathbf{A}_{11}^{-1}\)</span> where <span class="math inline">\(c = (a_{22} - \mathbf{a}_{12}^{\intercal}\mathbf{A}_{11}^{-1}\mathbf{a}_{12})^{-1}\)</span>. The profile sandwich uses <span class="math inline">\(\mathbf{A}_{11}^{-1}\)</span> as the bread, while the marginal <span class="math inline">\(\boldsymbol{\beta}\)</span>-block uses <span class="math inline">\([\mathbf{A}^{-1}]_{11}\)</span>. The difference <span class="math inline">\(\boldsymbol{\Delta}\)</span> arises from the rank-1 correction <span class="math inline">\(\mathbf{A}_{11}^{-1}\mathbf{a}_{12}\,c\,\mathbf{a}_{12}^{\intercal}\mathbf{A}_{11}^{-1}\)</span> propagated through the sandwich. <span class="math inline">\(\square\)</span></p>
<p>In practice, the profile sandwich produces results close to the full marginal sandwich for <span class="math inline">\(\boldsymbol{\beta}\)</span>. For the TSL15 data, the profile sandwich gives <span class="math inline">\(\mathrm{SD}(\mu) = 0.0216\)</span> versus the full marginal <span class="math inline">\(\mathrm{SD}(\mu) = 0.0244\)</span>, a gap of 11.5% attributable to <span class="math inline">\(\tau^2\)</span> estimation uncertainty.</p>
</section>
</section>
<section id="sec-sandwich-taxonomy" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="sec-sandwich-taxonomy"><span class="header-section-number">5.4.3</span> Definition 3b (Sandwich Variant Taxonomy)</h3>
<p>The preceding development yields four sandwich estimators for fixed-effect inference, forming a hierarchy from most to least conditioning. We define these formally for reference throughout the remainder of the text.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition 3b (Sandwich Variant Taxonomy)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(\boldsymbol{\phi} = (\boldsymbol{\beta}^{\intercal}, \boldsymbol{\theta}^{\intercal})^{\intercal} \in \mathbb{R}^{K+J}\)</span> be the full joint parameter and <span class="math inline">\(\boldsymbol{\xi} = (\boldsymbol{\beta}^{\intercal}, \tau^2)^{\intercal} \in \mathbb{R}^{K+1}\)</span> the marginal parameter. The four sandwich estimators for <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}})\)</span> are:</p>
<p><strong>(i) Full-joint conditional sandwich</strong> (<span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{cond}}\)</span>). The <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the <span class="math inline">\((K+J)\)</span>-dimensional sandwich from Definition 3: <span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{cond}}[\boldsymbol{\beta}] = \bigl[(\mathbf{H}^{\mathrm{post}})^{-1}\,\mathbf{M}\,(\mathbf{H}^{\mathrm{post}})^{-1}\bigr]_{\boldsymbol{\beta}\boldsymbol{\beta}}.
\]</span> This estimates <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}} \mid \hat{\boldsymbol{\theta}})\)</span>, the variance of the fixed effects <strong>conditional on the realized random effects</strong>. It is near zero when the posterior mean <span class="math inline">\(\hat{\boldsymbol{\theta}}\)</span> absorbs the study-level variation.</p>
<p><strong>(ii) Profile sandwich</strong> (<span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}}\)</span>). The <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the marginal sandwich with <span class="math inline">\(\tau^2\)</span> fixed at <span class="math inline">\(\hat{\tau}^2\)</span>: <span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}} = (H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}})^{-1}\,[\mathbf{M}_{\mathrm{marg}}]_{\boldsymbol{\beta}\boldsymbol{\beta}}\,(H_{\boldsymbol{\beta}\boldsymbol{\beta}}^{\mathrm{marg}})^{-1}.
\]</span> This estimates <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}} \mid \tau^2 = \hat{\tau}^2)\)</span>, conditioning on the heterogeneity variance but marginalizing over <span class="math inline">\(\boldsymbol{\theta}\)</span>.</p>
<p><strong>(iii) Bayesian marginal sandwich</strong> (<span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}\)</span>). The <span class="math inline">\(\boldsymbol{\beta}\)</span>-block of the <span class="math inline">\((K+1)\)</span>-dimensional marginal sandwich from Definition 3a: <span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}[\boldsymbol{\beta}] = \bigl[(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}})^{-1}\,\mathbf{M}_{\mathrm{marg}}\,(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post}})^{-1}\bigr]_{\boldsymbol{\beta}\boldsymbol{\beta}}.
\]</span> This estimates <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}})\)</span> marginalizing over both <span class="math inline">\(\boldsymbol{\theta}\)</span> and <span class="math inline">\(\tau^2\)</span>. It is the <strong>recommended CCC target</strong> for <span class="math inline">\(\boldsymbol{\beta}\)</span> (see <a href="ch06-posterior-ccc.html#sec-blockwise-ccc" class="quarto-xref"><span>Section 6.2.2</span></a>).</p>
<p><strong>(iv) Frequentist CR2 sandwich</strong> (<span class="math inline">\(\mathbf{V}_{\mathrm{CR2}}\)</span>). The cluster-robust variance estimator from the frequentist three-level meta-analytic model (e.g., via <code>clubSandwich::coef_test()</code>). This serves as an <strong>external validation</strong> benchmark, not a component of the Bayesian CCC pipeline.</p>
<p><strong>Ordering.</strong> For fixed effects in hierarchical models, these estimators satisfy: <span id="eq-sandwich-ordering"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{cond}}[\boldsymbol{\beta}] \;\ll\; \mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}} \;\lesssim\; \mathbf{V}_{\mathrm{CR2}} \;\lesssim\; \mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}[\boldsymbol{\beta}],
\tag{5.23}\]</span></span> where <span class="math inline">\(\ll\)</span> denotes “much smaller” and <span class="math inline">\(\lesssim\)</span> denotes “approximately less than or equal.” The first gap (<span class="math inline">\(\ll\)</span>) arises because the conditional sandwich treats <span class="math inline">\(\boldsymbol{\theta}\)</span> as fixed (ignoring the between-study variance contribution to <span class="math inline">\(\mathrm{Var}(\hat{\boldsymbol{\beta}})\)</span>), while the marginal sandwich integrates out <span class="math inline">\(\boldsymbol{\theta}\)</span> and captures the full between-study variation. The intermediate inequalities (<span class="math inline">\(\lesssim\)</span>) hold under the regularity that the profile and marginal scores have concordant covariance structure; a complete proof of the profile–CR2–marginal chain requires additional analysis of the cross-term contributions, which we defer.</p>
</div>
</div>
</section>
<section id="sec-marginal-sandwich-equiv" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="sec-marginal-sandwich-equiv"><span class="header-section-number">5.4.4</span> Proposition: Marginal Sandwich Equivalence</h3>
<p>Theorem 2 establishes the equivalence of the full-joint conditional sandwich (variant (i)) across the two frameworks. The following proposition extends this result to the Bayesian marginal sandwich (variant (iii)). Importantly, the proposition itself is <strong>abstract</strong>: it does not rely on the cluster-mean reduction above and therefore remains valid whenever the two frameworks share the same marginal Gaussian kernel after integrating out <span class="math inline">\(\boldsymbol{\theta}\)</span>. The cluster-mean formulas in Definition 3a are simply the closed-form special case used operationally in the intercept-only / study-level-covariate setting.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Proposition (Marginal Sandwich Equivalence)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under conditions (E1)–(E3) and (E5), suppose both frameworks use the same random-effects prior <span class="math inline">\(\theta_j \mid \tau^2 \sim \textsf{N}(0, \tau^2)\)</span>. Then the Bayesian marginal sandwiches are identical: <span id="eq-marginal-sandwich-equiv"><span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg},\,\mathrm{surv}} = \mathbf{V}_{\mathrm{sand}}^{\mathrm{marg},\,\mathrm{meta}}.
\tag{5.24}\]</span></span></p>
<p>In particular: (a) the marginal scores are identical: <span class="math inline">\(\mathbf{s}_j^{\mathrm{marg},\,\mathrm{surv}}(\boldsymbol{\xi}) = \mathbf{s}_j^{\mathrm{marg},\,\mathrm{meta}}(\boldsymbol{\xi})\)</span> for every <span class="math inline">\(j\)</span>; (b) the marginal Hessians are identical: <span class="math inline">\(\mathbf{H}_{\mathrm{marg}}^{\mathrm{surv}} = \mathbf{H}_{\mathrm{marg}}^{\mathrm{meta}}\)</span>; (c) the marginal meat matrices are identical; and (d) the full <span class="math inline">\((K+1)\)</span>-dimensional marginal sandwiches are identical.</p>
</div>
</div>
<p><strong>Proof.</strong> By Theorem 1, the joint log-likelihoods satisfy <span class="math inline">\(\ell_{\mathrm{surv}}^{(w)}(\boldsymbol{\phi}) = \ell_{\mathrm{meta}}(\boldsymbol{\phi}) + c\)</span>, where <span class="math inline">\(c = \sum_j c_j\)</span> is a constant that depends only on Level 1 quantities and not on <span class="math inline">\(\boldsymbol{\phi} = (\boldsymbol{\beta}^{\intercal}, \boldsymbol{\theta}^{\intercal})^{\intercal}\)</span>. As established in the Corollary 1 proof (<a href="ch06-posterior-ccc.html#sec-posterior-equiv" class="quarto-xref"><span>Section 6.1</span></a>), <span class="math inline">\(c\)</span> also does not depend on <span class="math inline">\(\tau^2\)</span>.</p>
<p>The marginal log-likelihood is obtained by integrating out <span class="math inline">\(\boldsymbol{\theta}\)</span> under the random-effects prior: <span class="math display">\[
\ell^{\mathrm{marg}}_{\mathrm{surv}}(\boldsymbol{\beta}, \tau^2) = \log \int \exp\!\left[\ell_{\mathrm{surv}}^{(w)}(\boldsymbol{\beta}, \boldsymbol{\theta})\right] \prod_{j=1}^{J} \textsf{N}(\theta_j \mid 0, \tau^2)\; d\boldsymbol{\theta}.
\]</span> Substituting <span class="math inline">\(\ell_{\mathrm{surv}}^{(w)} = \ell_{\mathrm{meta}} + c\)</span>: <span class="math display">\[
\ell^{\mathrm{marg}}_{\mathrm{surv}}(\boldsymbol{\beta}, \tau^2) = \log \int e^c \cdot \exp\!\left[\ell_{\mathrm{meta}}(\boldsymbol{\beta}, \boldsymbol{\theta})\right] \prod_j \textsf{N}(\theta_j \mid 0, \tau^2)\; d\boldsymbol{\theta} = c + \ell^{\mathrm{marg}}_{\mathrm{meta}}(\boldsymbol{\beta}, \tau^2).
\]</span> Since <span class="math inline">\(c\)</span> is constant with respect to <span class="math inline">\((\boldsymbol{\beta}, \tau^2)\)</span>, all derivatives of <span class="math inline">\(\ell^{\mathrm{marg}}\)</span> with respect to <span class="math inline">\(\boldsymbol{\xi} = (\boldsymbol{\beta}^{\intercal}, \tau^2)^{\intercal}\)</span> are identical across frameworks. In particular:</p>
<ol type="a">
<li><p><strong>Marginal scores</strong>: <span class="math inline">\(\nabla_{\boldsymbol{\xi}}\,\ell_j^{\mathrm{marg},\,\mathrm{surv}} = \nabla_{\boldsymbol{\xi}}\,\ell_j^{\mathrm{marg},\,\mathrm{meta}}\)</span> (since <span class="math inline">\(c_j\)</span> is <span class="math inline">\(\boldsymbol{\xi}\)</span>-free).</p></li>
<li><p><strong>Marginal Hessian</strong>: <span class="math inline">\(\mathbf{H}_{\mathrm{marg}}^{\mathrm{surv}} = -\nabla^2_{\boldsymbol{\xi}}\,\ell^{\mathrm{marg},\,\mathrm{surv}} = -\nabla^2_{\boldsymbol{\xi}}\,\ell^{\mathrm{marg},\,\mathrm{meta}} = \mathbf{H}_{\mathrm{marg}}^{\mathrm{meta}}\)</span>.</p></li>
<li><p><strong>Marginal meat</strong>: <span class="math inline">\(\mathbf{M}_{\mathrm{marg}}^{\mathrm{surv}} = \sum_j \mathbf{s}_j^{\mathrm{marg},\,\mathrm{surv}}\,(\mathbf{s}_j^{\mathrm{marg},\,\mathrm{surv}})^{\intercal} = \sum_j \mathbf{s}_j^{\mathrm{marg},\,\mathrm{meta}}\,(\mathbf{s}_j^{\mathrm{marg},\,\mathrm{meta}})^{\intercal} = \mathbf{M}_{\mathrm{marg}}^{\mathrm{meta}}\)</span> (by part (a)).</p></li>
<li><p><strong>Marginal sandwich</strong>: <span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg},\,\mathrm{surv}} = (\mathbf{H}_{\mathrm{marg}}^{\mathrm{post},\,\mathrm{surv}})^{-1}\,\mathbf{M}_{\mathrm{marg}}^{\mathrm{surv}}\,(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post},\,\mathrm{surv}})^{-1}\)</span>. By part (b) and the assumption of identical priors (<span class="math inline">\(\mathbf{H}_{\mathrm{prior}}\)</span> is the same), <span class="math inline">\(\mathbf{H}_{\mathrm{marg}}^{\mathrm{post},\,\mathrm{surv}} = \mathbf{H}_{\mathrm{marg}}^{\mathrm{post},\,\mathrm{meta}}\)</span>. Combined with part (c), the marginal sandwiches are identical. <span class="math inline">\(\quad\blacksquare\)</span></p></li>
</ol>
<p><strong>Remark.</strong> This proposition is the marginal-level analog of Theorem 2(d). The proof is immediate from the isomorphism (Theorem 1) because the additive constant <span class="math inline">\(c\)</span> is preserved under integration with respect to <span class="math inline">\(\boldsymbol{\theta}\)</span>. The result is used in the proof of Corollary 2 (Ingredient 3, <span class="math inline">\(\boldsymbol{\beta}\)</span>-block case) to justify the equivalence of the CCC target for fixed effects.</p>
<p><strong>Derivation of the ordering.</strong> To understand the ordering <a href="#eq-sandwich-ordering" class="quarto-xref">Equation&nbsp;<span>5.23</span></a>, consider the intercept-only CE model (<span class="math inline">\(K = 1\)</span>). At the posterior mean <span class="math inline">\(\hat{\boldsymbol{\xi}} = (\hat{\mu}, \hat{\tau}^2)^{\intercal}\)</span>, the marginal meat <span class="math inline">\(\boldsymbol{\beta}\)</span>-block is <span class="math inline">\(M_{\mu\mu}^{\mathrm{marg}} = \sum_j r_j^2 / v_j^2\)</span>, where <span class="math inline">\(r_j = \bar{y}_j - \hat{\mu}\)</span> and <span class="math inline">\(v_j = \bar{s}_j^2/n_j + \hat{\tau}^2\)</span>. Comparing:</p>
<ul>
<li><strong>Conditional meat</strong>: <span class="math inline">\(M_{\mu\mu}^{\mathrm{cond}} = \sum_j [n_j(\bar{y}_j - \hat{\mu} - \hat{\theta}_j)/\bar{s}_j^2]^2 \approx 0\)</span> (since <span class="math inline">\(\hat{\theta}_j \approx B_j r_j\)</span>, so <span class="math inline">\(\bar{y}_j - \hat{\mu} - \hat{\theta}_j \approx (1 - B_j)r_j \approx 0\)</span> when <span class="math inline">\(B_j \to 1\)</span>).</li>
<li><strong>Marginal meat</strong>: <span class="math inline">\(M_{\mu\mu}^{\mathrm{marg}} = \sum_j r_j^2 / v_j^2 &gt; 0\)</span> (no <span class="math inline">\(\hat{\theta}_j\)</span> to absorb residuals).</li>
</ul>
<p>The conditional sandwich scales as <span class="math inline">\(\mathrm{O}((1-B)^2)\)</span> while the marginal sandwich scales as <span class="math inline">\(\mathrm{O}(1)\)</span>, giving the <span class="math inline">\(\ll\)</span> relation.</p>
<p>The profile–CR2–marginal ordering arises because the profile sandwich uses <span class="math inline">\(H_{\mu\mu}^{-1} = 1/\sum_j v_j^{-1}\)</span> as the bread (conditioning on <span class="math inline">\(\tau^2\)</span>), while the full marginal sandwich propagates <span class="math inline">\(\tau^2\)</span> uncertainty through the off-diagonal Hessian blocks, widening the interval. The CR2 estimator from a 3-level model splits <span class="math inline">\(\tau^2\)</span> into between-study (<span class="math inline">\(\tau^2\)</span>) and within-study (<span class="math inline">\(\omega^2\)</span>) components, effectively conditioning on a finer variance decomposition and yielding estimates between the profile and marginal sandwiches.</p>
<p><strong>Connection to REML.</strong> The marginal log-likelihood <a href="#eq-marginal-loglik-j" class="quarto-xref">Equation&nbsp;<span>5.11</span></a> has the same structure as the restricted maximum likelihood (REML) objective for a random-effects model. Specifically, the REML estimating equation for <span class="math inline">\(\tau^2\)</span> is <span class="math inline">\(\sum_j [(r_j^2 - v_j)/v_j^2] = 0\)</span>, which is exactly the sum of marginal <span class="math inline">\(\tau^2\)</span>-scores set to zero: <span class="math inline">\(\sum_j s_j(\tau^2) = 0\)</span> at the REML estimate. The Bayesian marginal sandwich can thus be viewed as a Bayesian robustification of the REML-based inference: it uses the same marginal model structure but replaces the asymptotic REML variance with the sandwich estimator that is consistent even when the marginal model is misspecified (e.g., when the true within-study structure is not compound symmetric).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Numerical Comparison: TSL15 Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Using the TSL15 data (<span class="math inline">\(J = 117\)</span>, <span class="math inline">\(N = 1{,}198\)</span>), the four sandwich estimators for <span class="math inline">\(\mathrm{SD}(\mu)\)</span> are compared, illustrating the ordering from Definition 3b:</p>
<div id="tbl-sandwich-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sandwich-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Comparison of sandwich estimators for the TSL15 data, ordered by conditioning level.
</figcaption>
<div aria-describedby="tbl-sandwich-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 35%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Variant</th>
<th style="text-align: center;">Dimension</th>
<th style="text-align: center;"><span class="math inline">\(\mathrm{SD}(\mu)\)</span></th>
<th style="text-align: center;">DER<span class="math inline">\(_\mu\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Full-joint (conditional)</td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{cond}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(K + J = 118\)</span></td>
<td style="text-align: center;">0.0069</td>
<td style="text-align: center;">0.096</td>
</tr>
<tr class="even">
<td style="text-align: left;">Profile (<span class="math inline">\(\tau^2\)</span> fixed)</td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{profile}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(K = 1\)</span></td>
<td style="text-align: center;">0.0216</td>
<td style="text-align: center;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CR2 (frequentist, 3-level)</td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{V}_{\mathrm{CR2}}\)</span></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">0.0206</td>
<td style="text-align: center;">0.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marginal joint (<span class="math inline">\(\boldsymbol{\beta}, \tau^2\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{V}_{\mathrm{sand}}^{\mathrm{marg}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(K + 1 = 2\)</span></td>
<td style="text-align: center;">0.0244</td>
<td style="text-align: center;">1.21</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The ordering <span class="math inline">\(0.0069 \ll 0.0216 \approx 0.0206 &lt; 0.0244\)</span> confirms the theoretical hierarchy. The Bayesian marginal sandwich gives <span class="math inline">\(\mathrm{DER}_\mu^{\mathrm{marg}} = 1.21 &gt; 1\)</span>, indicating that the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block CCC should be <strong>applied</strong> (widening the posterior). This contrasts with the CR2-based <span class="math inline">\(\mathrm{DER}_\mu^{\mathrm{CR2}} = 0.86 &lt; 1\)</span>, which previously led to skipping the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block CCC.</p>
<p><strong>Mathematical explanation of the 18.5% gap.</strong> The gap between the marginal sandwich (<span class="math inline">\(\mathrm{SD} = 0.0244\)</span>) and the CR2 (<span class="math inline">\(\mathrm{SE} = 0.0206\)</span>) arises from a structural model difference. The 2-level Bayesian model has marginal variance <span class="math inline">\(v_j^{(2)} = \bar{s}_j^2/n_j + \tau^2\)</span> with a single <span class="math inline">\(\hat{\tau}^2 = 0.0464\)</span>. The 3-level metafor model has <span class="math inline">\(v_j^{(3)} = s_{ij}^2 + \omega^2 + \tau^2\)</span> with <span class="math inline">\(\hat{\tau}^2 = 0.0397\)</span> and <span class="math inline">\(\hat{\omega}^2 = 0.0029\)</span>. Because <span class="math inline">\(\hat{\tau}^2_{(2)} &gt; \hat{\tau}^2_{(3)}\)</span> (the 2-level model absorbs <span class="math inline">\(\omega^2\)</span> into <span class="math inline">\(\tau^2\)</span>), the 2-level marginal weights <span class="math inline">\(w_j^{(2)} = 1/v_j^{(2)}\)</span> are slightly <strong>smaller</strong> than the 3-level weights, yielding a slightly larger sandwich variance. Formally, the marginal sandwich SD satisfies <span class="math display">\[
\frac{\mathrm{SD}_{\mathrm{sand}}^{\mathrm{marg}}}{\mathrm{SE}_{\mathrm{CR2}}} = \frac{0.0244}{0.0206} = 1.185,
\]</span> and this factor is driven by the propagation of <span class="math inline">\(\tau^2\)</span> estimation uncertainty through the <span class="math inline">\((K+1)\)</span>-dimensional inverse. The profile sandwich, which conditions on <span class="math inline">\(\tau^2\)</span> and uses only the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block, eliminates this source of discrepancy: <span class="math inline">\(\mathrm{SD}_{\mathrm{profile}} / \mathrm{SE}_{\mathrm{CR2}} = 0.0216/0.0206 = 1.049\)</span>, a 5.1% gap consistent with the residual difference in weighting structure between the 2-level and 3-level models.</p>
</div>
</div>
</div>
<p><strong>Key advantage: purely Bayesian.</strong> The Bayesian marginal sandwich (Definition 3a) eliminates the dependency on frequentist CR2 packages (e.g., <code>clubSandwich</code>) for the <span class="math inline">\(\boldsymbol{\beta}\)</span>-block CCC. All ingredients — the marginal scores, the marginal Hessian, and the posterior draws — come from the same Bayesian model. The CR2 estimator remains available as an <strong>external validation</strong> tool for cross-checking the marginal sandwich (variant (iv) in the taxonomy), but it is no longer a required component of the CCC pipeline. This is discussed further in <a href="ch06-posterior-ccc.html#sec-blockwise-ccc" class="quarto-xref"><span>Section 6.2.2</span></a>.</p>
</section>
<section id="sec-remark-small-sample" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="sec-remark-small-sample"><span class="header-section-number">5.4.5</span> Remark 5 (Small-Sample Corrections: HC<span class="math inline">\(a\)</span> = CR<span class="math inline">\(a\)</span>)</h3>
<p>The baseline sandwich <a href="#eq-sandwich-def" class="quarto-xref">Equation&nbsp;<span>5.1</span></a> is the CR0 (equivalently, HC0) estimator. In finite samples, this estimator is biased downward, and several small-sample corrections have been proposed. The meta-analytic literature uses the CR<span class="math inline">\(a\)</span> family <span class="citation" data-cites="PustejovskyTipton2022 BellMcCaffrey2002">(<a href="#ref-PustejovskyTipton2022" role="doc-biblioref">Pustejovsky and Tipton 2022</a>; <a href="#ref-BellMcCaffrey2002" role="doc-biblioref">Bell and McCaffrey 2002</a>)</span>, while the survey literature uses the corresponding HC<span class="math inline">\(a\)</span> family <span class="citation" data-cites="MacKinnonWhite1985">(<a href="#ref-MacKinnonWhite1985" role="doc-biblioref">MacKinnon and White 1985</a>)</span>. The corrections are defined by replacing the raw cluster-level residual vector <span class="math inline">\(\mathbf{e}_j = \mathbf{y}_j - \mathbf{X}_j\hat{\boldsymbol{\beta}} - \hat{\theta}_j\mathbf{1}_{n_j}\)</span> with an adjusted residual <span class="math inline">\(\mathbf{A}_j^{(a)}\mathbf{e}_j\)</span> before forming the score outer products.</p>
<p>Specifically:</p>
<ul>
<li><strong>CR0 = HC0</strong>: No adjustment; <span class="math inline">\(\mathbf{A}_j^{(0)} = \mathbf{I}_{n_j}\)</span>.</li>
<li><strong>CR1 = HC1</strong>: Degrees-of-freedom correction; <span class="math inline">\(\mathbf{A}_j^{(1)} = \sqrt{J/(J-p)}\,\mathbf{I}_{n_j}\)</span>.</li>
<li><strong>CR2 = HC2</strong>: Leverage-based correction; <span class="math inline">\(\mathbf{A}_j^{(2)} = (\mathbf{I}_{n_j} - \mathbf{P}_j)^{-1/2}\)</span> where <span class="math inline">\(\mathbf{P}_j\)</span> is the leverage matrix for cluster <span class="math inline">\(j\)</span>.</li>
<li><strong>CR3 = HC3</strong>: Jackknife-type correction; <span class="math inline">\(\mathbf{A}_j^{(3)} = (\mathbf{I}_{n_j} - \mathbf{P}_j)^{-1}\)</span>.</li>
</ul>
<p>Under (E1)–(E3) and (E5):</p>
<ol type="1">
<li>The residuals <span class="math inline">\(\mathbf{e}_j\)</span> are identical (same likelihood, same <span class="math inline">\(\hat{\boldsymbol{\phi}}\)</span>, same design matrices).</li>
<li>The leverage matrices <span class="math inline">\(\mathbf{P}_j\)</span> are identical (they depend on <span class="math inline">\(\mathbf{X}_j\)</span>, <span class="math inline">\(\boldsymbol{\Sigma}_j^{\mathrm{work}}\)</span>, and <span class="math inline">\(\mathbf{H}\)</span>, all of which are matched).</li>
<li>The adjustment matrices <span class="math inline">\(\mathbf{A}_j^{(a)}\)</span> are therefore identical.</li>
</ol>
<p>Consequently, the adjusted meat and the corrected sandwich are identical across frameworks for every value of <span class="math inline">\(a\)</span>: <span class="math display">\[
\mathbf{V}_{\mathrm{sand}}^{\mathrm{surv},\,\mathrm{HC}a} = \mathbf{V}_{\mathrm{sand}}^{\mathrm{meta},\,\mathrm{CR}a}, \quad a = 0, 1, 2, 3.
\]</span></p>
<p>This extends Theorem 2 to the entire family of small-sample robust variance estimators in current use.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Novel Contribution: HC = CR as Structural Consequence
</div>
</div>
<div class="callout-body-container callout-body">
<p>The numerical identity HC<span class="math inline">\(a\)</span> = CR<span class="math inline">\(a\)</span> (for <span class="math inline">\(a = 0, 1, 2, 3\)</span>) is <strong>not stated in the prior literature</strong>. It is a structural consequence of the likelihood isomorphism (Theorem 1, <a href="ch04-isomorphism.html" class="quarto-xref"><span>Chapter 4</span></a>) and the sandwich equivalence (Theorem 2, <a href="#sec-sandwich" class="quarto-xref"><span>Chapter 5</span></a>). While the HC and CR families were developed independently — HC in the heteroskedasticity-consistent estimator literature <span class="citation" data-cites="MacKinnonWhite1985 CameronMiller2015">(<a href="#ref-MacKinnonWhite1985" role="doc-biblioref">MacKinnon and White 1985</a>; <a href="#ref-CameronMiller2015" role="doc-biblioref">Cameron and Miller 2015</a>)</span> and CR in the meta-analytic cluster-robust literature <span class="citation" data-cites="BellMcCaffrey2002 PustejovskyTipton2022">(<a href="#ref-BellMcCaffrey2002" role="doc-biblioref">Bell and McCaffrey 2002</a>; <a href="#ref-PustejovskyTipton2022" role="doc-biblioref">Pustejovsky and Tipton 2022</a>)</span> — the present result reveals that they are mathematically identical under the exactness conditions (E1)–(E3) and (E5).</p>
<p>A key structural distinction remains: the survey HC estimator operates at the <strong>PSU (primary sampling unit) level</strong>, while the meta-analytic CR estimator operates at the <strong>study level</strong>. The isomorphism identifies these two clustering units (<span class="math inline">\(\text{PSU} \leftrightarrow \text{study}\)</span>), and the HC = CR identity follows.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-BellMcCaffrey2002" class="csl-entry" role="listitem">
Bell, Robert M., and Daniel F. McCaffrey. 2002. <span>“Bias Reduction in Standard Errors for Linear Regression with Multi-Stage Samples.”</span> <em>Survey Methodology</em> 28 (2): 169–81.
</div>
<div id="ref-CameronMiller2015" class="csl-entry" role="listitem">
Cameron, A. Colin, and Douglas L. Miller. 2015. <span>“A Practitioner’s Guide to Cluster-Robust Inference.”</span> <em>Journal of Human Resources</em> 50 (2): 317–72. <a href="https://doi.org/10.3368/jhr.50.2.317">https://doi.org/10.3368/jhr.50.2.317</a>.
</div>
<div id="ref-MacKinnonWhite1985" class="csl-entry" role="listitem">
MacKinnon, James G., and Halbert White. 1985. <span>“Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties.”</span> <em>Journal of Econometrics</em> 29 (3): 305–25. <a href="https://doi.org/10.1016/0304-4076(85)90158-7">https://doi.org/10.1016/0304-4076(85)90158-7</a>.
</div>
<div id="ref-PustejovskyTipton2022" class="csl-entry" role="listitem">
Pustejovsky, James E., and Elizabeth Tipton. 2022. <span>“Meta-Analysis with Robust Variance Estimation: Expanding the Range of Working Models.”</span> <em>Prevention Science</em> 23 (3): 425–38. <a href="https://doi.org/10.1007/s11121-021-01246-3">https://doi.org/10.1007/s11121-021-01246-3</a>.
</div>
<div id="ref-WilliamsSavitsky2021" class="csl-entry" role="listitem">
Williams, Matthew R., and Terrance D. Savitsky. 2021. <span>“Uncertainty Estimation for Pseudo-<span>B</span>ayesian Inference Under Complex Sampling.”</span> <em>International Statistical Review</em> 89 (1): 72–107. <a href="https://doi.org/10.1111/insr.12376">https://doi.org/10.1111/insr.12376</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch04-isomorphism.html" class="pagination-link" aria-label="Theorem 1: Likelihood Isomorphism">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Theorem 1: Likelihood Isomorphism</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch06-posterior-ccc.html" class="pagination-link" aria-label="Corollaries 1--2: Posterior and CCC Equivalence">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Corollaries 1–2: Posterior and CCC Equivalence</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/joonho112/bayesian-meta-survey-equivalence/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>